In [2]:
# 1. Import the numpy package under the name np
import numpy as np

In [4]:
# 2. Print the numpy version and the configuration
print(np.__version__)
#np.show_config()

1.24.2


In [8]:
# 3. Create a null Vector of size 10
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
# 4. How to find the memory size of any array
Z = np.zeros((10, 10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# 5. How to get the documentation of the numpy add function from the command line
```
%run `python -c "import numpy; numpy.info(numpy.add)"`
```

In [11]:
# 6. Create a null vector of size 10 but the fifth value witch is 1
Z = np.empty(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [12]:
# 7. Create a vector with values ranging from 10 to 49
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [13]:
# 8. Reverse a vector (first element becomes last)
Z = np.arange(10, 50)
print(Z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [16]:
# 9. Create a 3x3 matrix with values ranging from 0 to 8
Z = np.arange(1, 10).reshape(3, 3)
print(Z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


In [3]:
#11. Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [5]:
# 12. Create a 3x3x3 array with random values
rd = np.random.random([3,3,3])
rd

array([[[0.70628239, 0.22470743, 0.39232807],
        [0.84797768, 0.77896775, 0.28406007],
        [0.14093468, 0.52640479, 0.48179621]],

       [[0.08804447, 0.85802704, 0.74467435],
        [0.91679891, 0.19201535, 0.80454416],
        [0.80854594, 0.82295466, 0.10778269]],

       [[0.0365027 , 0.33619927, 0.47329974],
        [0.49048305, 0.10555753, 0.5091751 ],
        [0.38740919, 0.20508485, 0.40068484]]])

In [9]:
# 13. Create a 10x10 array with random values and find the minimum and maximum values

rd = np.random.random([10, 10])
print(np.min(rd), np.max(rd))
print(rd.min(), rd.max())

0.0022239177823975 0.9804838375552981
0.0022239177823975 0.9804838375552981


In [10]:
# 14. Create a random vector of size 30 and find the mean value
re = np.random.random(30)
print(np.mean(re), re.mean())

0.5095822761009964